const menu = [
  {
    id: 1,
    title: 'Classic Fries',
    category: 'Potato Family',
    price: 60,
  },
  {
    id: 2,
    title: 'Peri Peri Fries',
    category: 'Potato Family',
    price: 70,
  },
  {
    id: 3,
    title: 'Cheese Fries',
    category: 'Potato Family',
    price: 80,
  },
  {
    id: 4,
    title: 'Smilies',
    category: 'Potato Family',
    price: 60,
  },
  {
    id: 5,
    title: 'Veg Cutlet',
    category: 'Potato Family',
    price: 40,
  },
  {
    id: 6,
    title: 'Cheese Ball',
    category: 'Potato Family',
    price: 70,
  },
  {
    id: 7,
    title: 'Cheese corn triangle',
    category: 'Potato Family',
    price: 80,
  },
  {
    id: 8,
    title: 'Potato Wedges',
    category: 'Potato Family',
    price: 70,
  },
  {
    id: 9,
    title: 'Aloo Kabab',
    category: 'Potato Family',
    price: 70,
  },
  {
    id: 10,
    title: 'Gobi 65',
    category: 'Starters',
    price: 60,
  },
  {
    id: 11,
    title: 'Mushroom 65',
    category: 'Starters',
    price: 70,
  },
  {
    id: 12,
    title: 'Paneer 65',
    category: 'Starters',
    price: 80,
  },
  {
    id: 13,
    title: 'Babycorn 65',
    category: 'Starters',
    price: 70,
  },
  {
    id: 14,
    title: 'Pepper Babycorn 65',
    category: 'Starters',
    price: 80,
  },
  {
    id: 15,
    title: 'Gobi Chilly',
    category: 'Starters',
    price: 80,
  },
  {
    id: 16,
    title: 'Mushroom Chilly',
    category: 'Starters',
    price: 90,
  },
  {
    id: 17,
    title: 'Paneer Chilly',
    category: 'Starters',
    price: 90,
  },
  {
    id: 18,
    title: 'Babycorn Chilly',
    category: 'Starters',
    price: 90,
  },
  {
    id: 19,
    title: 'Gobi Manchurian',
    category: 'Starters',
    price: 70,
  },
  {
    id: 20,
    title: 'Mushroom Manchurian',
    category: 'Starters',
    price: 80,
  },
  {
    id: 21,
    title: 'Paneer Manchurian',
    category: 'Starters',
    price: 90,
  },
  {
    id: 22,
    title: 'Babycorn Manchurian',
    category: 'Starters',
    price: 80,
  },
  {
    id: 23,
    title: 'Masala Maggie',
    category: 'Maggie',
    price: 50,
  },
  {
    id: 24,
    title: 'Cheese Maggie',
    category: 'Maggie',
    price: 60,
  },
  {
    id: 25,
    title: 'Paneer and corn Maggie',
    category: 'Maggie',
    price: 60,
  },
  {
    id: 26,
    title: 'White Sauce Pasta',
    category: 'Pasta Paradise',
    price: 120,
  },
  {
    id: 27,
    title: 'Red Sauce Pasta',
    category: 'Pasta Paradise',
    price: 120,
  },
  {
    id: 28,
    title: 'Mixed Sauce Pasta',
    category: 'Pasta Paradise',
    price: 130,
  },
  {
    id: 29,
    title: 'Veg busted grill',
    category: 'Sandwiches',
    price: 70,
  },
  {
    id: 30,
    title: 'Cheesy paneer grill',
    category: 'Sandwiches',
    price: 80,
  },
  {
    id: 31,
    title: 'Cheesy corn',
    category: 'Sandwiches',
    price: 70,
  },
  {
    id: 32,
    title: 'Chef special sandwich',
    category: 'Sandwiches',
    price: 80,
  },
  {
    id: 33,
    title: 'Veg Steam Momo',
    category: 'Momo Club',
    price: 60,
  },
  {
    id: 34,
    title: 'Veg Fried Momo',
    category: 'Momo Club',
    price: 70,
  },
  {
    id: 35,
    title: 'Paneer Steam Momo',
    category: 'Momo Club',
    price: 70,
  },
  {
    id: 36,
    title: 'Paneer Fried Momo',
    category: 'Momo Club',
    price: 80,
  },
  {
    id: 37,
    title: 'Momos Manchurian',
    category: 'Momo Club',
    price: 80,
  },
  {
    id: 38,
    title: 'Chilly Momos',
    category: 'Momo Club',
    price: 80,
  },
  {
    id: 39,
    title: 'Veg Fried Rice',
    category: 'Rice Family',
    price: 70,
  },
  {
    id: 40,
    title: 'Paneer Fried Rice',
    category: 'Rice Family',
    price: 80,
  },
  {
    id: 41,
    title: 'Mushroom Fried Rice',
    category: 'Rice Family',
    price: 80,
  },
  {
    id: 42,
    title: 'Schezwan Fried Rice',
    category: 'Rice Family',
    price: 90,
  },
  {
    id: 43,
    title: 'Paneer Lovers',
    category: 'Pizza Club',
    price: 129,
  },
  {
    id: 44,
    title: 'Cheesy Mushroom',
    category: 'Pizza Club',
    price: 129,
  },
  {
    id: 45,
    title: 'Golden Corn Margarita',
    category: 'Pizza Club',
    price: 119,
  },
  {
    id: 46,
    title: 'Buzz Club Loaded',
    category: 'Pizza Club',
    price: 149,
  },
  {
    id: 47,
    title: 'Veg cheese loaded',
    category: 'Burger Feast',
    price: 70,
  },
  {
    id: 48,
    title: 'Aloo tikki',
    category: 'Burger Feast',
    price: 70,
  },
  {
    id: 49,
    title: 'Crispy paneer patty',
    category: 'Burger Feast',
    price: 80,
  },
  {
    id: 50,
    title: 'Buzz club maharaja meal',
    category: 'Burger Feast',
    price: 119,
  },
  {
    id: 51,
    title: 'Veg Noodles',
    category: 'Noodles Family',
    price: 70,
  },
  {
    id: 52,
    title: 'Chilly Garlic Noodles',
    category: 'Noodles Family',
    price: 80,
  },
  {
    id: 53,
    title: 'Schezwan Noodles',
    category: 'Noodles Family',
    price: 90,
  },
  {
    id: 54,
    title: 'Mushroom Mix Noodles',
    category: 'Noodles Family',
    price: 90,
  },
  {
    id: 55,
    title: 'Paneer Mix Noodles',
    category: 'Noodles Family',
    price: 90,
  },
  {
    id: 56,
    title: 'Gobi Mix Noodles',
    category: 'Noodles Family',
    price: 80,
  },
  {
    id: 57,
    title: 'Cold Coffee',
    category: 'Milkshakes',
    price: 60,
  },
  {
    id: 58,
    title: 'Chikoo Milkshake',
    category: 'Milkshakes',
    price: 70,
  },
  {
    id: 59,
    title: 'Oreo Milkshake',
    category: 'Milkshakes',
    price: 80,
  },
  {
    id: 60,
    title: 'Kitkat Milkshake',
    category: 'Milkshakes',
    price: 80,
  },
  {
    id: 61,
    title: 'Chocolate blend',
    category: 'Sweet Blend Milkshakes',
    price: 100,
  },
  {
    id: 62,
    title: 'Oreo blend',
    category: 'Sweet Blend Milkshakes',
    price: 100,
  },
  {
    id: 63,
    title: 'Lemon Soda',
    category: 'Mojito',
    price: 40,
  },
  {
    id: 64,
    title: 'Virgin Mojito',
    category: 'Mojito',
    price: 70,
  },
  {
    id: 65,
    title: 'Watermelon Mojito',
    category: 'Mojito',
    price: 80,
  },
  {
    id: 66,
    title: 'Blueberry Mojito',
    category: 'Mojito',
    price: 80,
  },
  {
    id: 67,
    title: 'Kiwi Mojito',
    category: 'Mojito',
    price: 90,
  },
  {
    id: 68,
    title: 'Vanilla',
    category: 'Ice-Creams',
    price: 40,
  },
  {
    id: 69,
    title: 'Chocoloate',
    category: 'Ice-Creams',
    price: 50,
  },
  {
    id: 70,
    title: 'Mango',
    category: 'Ice-Creams',
    price: 50,
  },
  {
    id: 71,
    title: 'ButterScotch',
    category: 'Ice-Creams',
    price: 60,
  },
  {
    id: 72,
    title: 'BlackCurrent',
    category: 'Ice-Creams',
    price: 60,
  },




];
export default menu;
